addSbtPlugin("org.scalameta"             % "sbt-scalafmt"       % "2.4.6")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"       % "0.4.1")
addSbtPlugin("com.github.sbt"            % "sbt-github-actions" % "0.24.0")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"     % "1.9.2")
addSbtPlugin("com.timushev.sbt"          % "sbt-rewarn"         % "0.1.3")
